# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/LAB_VNU/axi_becvip2/axi_becvip2.srcs/sources_1/bd/axi_becvip2/ip/axi_becvip2_axi_vip_0_0/axi_becvip2_axi_vip_0_0.xci
# IP: The module: 'axi_becvip2_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LAB_VNU/axi_becvip2/axi_becvip2.gen/sources_1/bd/axi_becvip2/ip/axi_becvip2_axi_vip_0_0/axi_becvip2_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_becvip2_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/LAB_VNU/axi_becvip2/axi_becvip2.srcs/sources_1/bd/axi_becvip2/ip/axi_becvip2_axi_vip_0_0/axi_becvip2_axi_vip_0_0.xci
# IP: The module: 'axi_becvip2_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LAB_VNU/axi_becvip2/axi_becvip2.gen/sources_1/bd/axi_becvip2/ip/axi_becvip2_axi_vip_0_0/axi_becvip2_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_becvip2_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
